### PR TITLE
hotfix issue #9 add regex

### PR DESCRIPTION
**Pull request by zonky2**
hotfix issue #9 add regex

### CODE REVIEW

**Comment by richardhj** [comment]
This will only work, if the `attribute_text` is installed too. This is because the event listener is part of this package. See https://github.com/MetaModels/attribute_text/blob/master/src/MetaModels/Attribute/Text/BackendSubscriber.php#L53-L59
And technically, the `attribute_text` is no requirement of the `attribute_translatedtext`.

**Comment by zonky2** [comment]
@richardhj that´s right - we should determine whether the translated attributes need their non-translated attributes as dependency rules

**Comment by zonky2** [comment]
MM call 26.09.2017: attribute_translatedtext should have no dependency on attribute_text

**Comment by zonky2** [comment]
done

fireshot pro screen capture 075 - trans_test - contao open source cms 3_5 - c2g_local_vhosts_contao-3_5_x_contao_main_php_do metamodel_mm_trans_tes

**Comment by discordier** [comment]
Merged in 090d896450eea1f328549317fe0296d715527e6f

**Pull request closed without merging**
